spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: reactiveSpringMongo
      authentication-database: admin
      port: 27017
      host: localhost

springdoc:
  webjars:
    prefix: /api-doc
  api-docs:
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

encrypt:
  key: 6065b73a-f0b7-4b61-a845-94fdf23de233
